# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\x12\x05lab_6\"\x1e\n\x06\x61\x64\x64Msg\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\x1a\n\x0brawImageMsg\x12\x0b\n\x03img\x18\x01 \x01(\x0c\"%\n\rdotProductMsg\x12\t\n\x01\x61\x18\x01 \x03(\x02\x12\t\n\x01\x62\x18\x02 \x03(\x02\"\x1b\n\x0cjsonImageMsg\x12\x0b\n\x03img\x18\x01 \x01(\t\"\x1a\n\x0b\x61\x64\x64MsgReply\x12\x0b\n\x03sum\x18\x01 \x01(\x05\"+\n\x12\x64otProductMsgReply\x12\x15\n\rdotProductSum\x18\x01 \x03(\x02\"1\n\x10rawImageMsgReply\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\"2\n\x11jsonImageMsgReply\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x32\xe5\x01\n\x05Lab_6\x12(\n\x03\x61\x64\x64\x12\r.lab_6.addMsg\x1a\x12.lab_6.addMsgReply\x12\x37\n\x08rawimage\x12\x12.lab_6.rawImageMsg\x1a\x17.lab_6.rawImageMsgReply\x12=\n\ndotproduct\x12\x14.lab_6.dotProductMsg\x1a\x19.lab_6.dotProductMsgReply\x12:\n\tjsonimage\x12\x13.lab_6.jsonImageMsg\x1a\x18.lab_6.jsonImageMsgReplyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ADDMSG._serialized_start=25
  _ADDMSG._serialized_end=55
  _RAWIMAGEMSG._serialized_start=57
  _RAWIMAGEMSG._serialized_end=83
  _DOTPRODUCTMSG._serialized_start=85
  _DOTPRODUCTMSG._serialized_end=122
  _JSONIMAGEMSG._serialized_start=124
  _JSONIMAGEMSG._serialized_end=151
  _ADDMSGREPLY._serialized_start=153
  _ADDMSGREPLY._serialized_end=179
  _DOTPRODUCTMSGREPLY._serialized_start=181
  _DOTPRODUCTMSGREPLY._serialized_end=224
  _RAWIMAGEMSGREPLY._serialized_start=226
  _RAWIMAGEMSGREPLY._serialized_end=275
  _JSONIMAGEMSGREPLY._serialized_start=277
  _JSONIMAGEMSGREPLY._serialized_end=327
  _LAB_6._serialized_start=330
  _LAB_6._serialized_end=559
# @@protoc_insertion_point(module_scope)
